import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#17211b',
  muted: '#68756d',
  line: '#dce5de',
  surface: '#ffffff',
  soft: '#f4f8f4',
  green: '#19734a',
  darkGreen: '#105737',
  greenSoft: '#e8f4e9',
  accent: '#e9a83a',
  danger: '#b33d3d',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.soft },
  content: { padding: 18, paddingBottom: 40 },
  title: { color: colors.ink, fontSize: 30, fontWeight: '800', letterSpacing: -0.7 },
  subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  sectionTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '800',
    marginTop: 24,
    marginBottom: 10,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
  },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 10,
    color: colors.ink,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 16,
  },
  label: { color: colors.ink, fontSize: 13, fontWeight: '700', marginBottom: 6 },
  primary: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 11,
    paddingVertical: 13,
  },
  primaryText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  secondary: {
    alignItems: 'center',
    backgroundColor: colors.soft,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 11,
    paddingVertical: 12,
  },
  secondaryText: { color: colors.darkGreen, fontSize: 15, fontWeight: '800' },
  danger: {
    alignItems: 'center',
    backgroundColor: '#fff7f7',
    borderColor: '#efcaca',
    borderWidth: 1,
    borderRadius: 11,
    paddingVertical: 12,
  },
  error: {
    backgroundColor: '#fff7f7',
    borderColor: '#efcaca',
    borderWidth: 1,
    borderRadius: 10,
    color: colors.danger,
    marginBottom: 12,
    padding: 11,
  },
  success: {
    backgroundColor: colors.greenSoft,
    borderColor: '#cfe4d3',
    borderWidth: 1,
    borderRadius: 10,
    color: colors.darkGreen,
    marginBottom: 12,
    padding: 11,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  spaceBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  badge: {
    backgroundColor: colors.greenSoft,
    borderRadius: 99,
    color: colors.darkGreen,
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
});
